### ISSUE TITLE
Portuguese WiKi link

### ISSUE THREAD

**Issue by hugok79** [DidierSpaier/slint-website#1]
Under portuguese language, https://slint.fr/pt/home.html if you select the WiKi, it gives you a bad lang code link. https://slint.fr/pt_PT/wiki.html

Should point to https://slint.fr/pt/wiki.html instead.

If you choose https://slint.fr/en/wiki.html and then select the **pt** language, it works fine

**Comment by hugok79** [comment]
@DidierSpaier As you know, Portuguese uses **pt** or **pt_PT**

This is an old problem beacuase of the **pt_BR**(Brazilian Portuguese) variant of the Portuguese Language...

**Comment by hugok79** [comment]
It also happens in https://slint.fr/pt_PT/oldHandBook.html

https://slint.fr/pt/oldHandBook.html works fine

![Captura de ecrã 2023-03-06 112553](https://user-images.githubusercontent.com/16929048/223097507-dc5b0fbe-7eee-4117-9c2b-6ebed5822ea8.png)

**Comment by DidierSpaier** [comment]
Yes, I have fix that  fix that. I think we should use always use pt_PT to avoid any confusion.
... Or maybe tag pt for pt_PT and pt_BR for pt_BR?

**Comment by DidierSpaier** [comment]
Should be fixed now in all pages. I used pt for pt_PT.

**Comment by hugok79** [comment]
> Under portuguese language, https://slint.fr/pt/home.html if you select the WiKi, it gives you a bad lang code link. https://slint.fr/pt_PT/wiki.html
> 
> Should point to https://slint.fr/pt/wiki.html instead.
> 
> If you choose https://slint.fr/en/wiki.html and then select the **pt** language, it works fine

* Not fixed yet

**Comment by DidierSpaier** [comment]
It Works Here (TM). My assumption is that you have to reload all visited pages of the website (or clear the cache of the web browser), as I had to do that too.

**Comment by DidierSpaier** [comment]
... But the issue for the "translated but displayed in English" strings remains and it exist in all locales. I am going to upgrade po4a then if it is not enough to solve it post the issue on the po4a mailing list.

**Comment by hugok79** [comment]
> It Works Here (TM). My assumption is that you have to reload all visited pages of the website (or clear the cache of the web browser), as I had to do that too.

it keeps happening @DidierSpaier

Go to https://slint.fr/pt/home.html and then click in the **WiKi**
Opens the following https://slint.fr/pt_PT/wiki.html (pt_PT)
Only this works https://slint.fr/pt/wiki.html (pt)


Under **headers/pt_PT.header.adoc**
           * link:../pt_PT/wiki.html[WiKi]

**Comment by DidierSpaier** [comment]
Good catch Hugo! should be fixed now.
